### PR TITLE
[EnemyControl] Fix #8

### LINKED ISSUE #8: [EnemyControl] Dropdown might not accurately display preset
Might get stuck displaying incorrect preset

### PR DESCRIPTION
**Pull request by SleepSoul**
ReadPreset and UpdatePools were not correctly clearing EligibleEnemies and EnemySets. These will both now reset to default before preset is read, so you won't have carryover from the previous setting and it'll be correctly reapplied.

### CODE REVIEW

File: EnemyControl/EnemyControl.lua [hunk 1]
```diff
@@ -145,14 +146,31 @@ function EnemyControl.ReadPreset() --Read current preset and create table of ene
...
-        EnemyControl.Pool = pool
-        ModUtil.Table.Replace(EnemySets[EnemyControl.Target], EnemyControl.Pool)
+    local target = nil
+    for biome, pool in pairs( EnemyControl.EligibleEnemies ) do
+        target = RCLib.EncodeEnemySet( biome )
+        EnemySets[target] = ModUtil.Table.Copy( pool )
         DebugPrint({Text = "Updated enemy pool for "..biome})
     end
+    for encounter, data in pairs( EncounterData ) do -- If EnemySets is updated without updating EncounterData to match, behaviour is unreliable. Inheritance first
+        if data.InheritFrom then
```
Comment (Zyruvias) [inline EnemyControl/EnemyControl.lua:159]: can we run `ProcessDataInheritence` here? SGG framework level code should be used as much as possible for consistency.

Comment (SleepSoul) [reply EnemyControl/EnemyControl.lua]: Agreed that this is better, changed in new commit
